"""
BIRD configuration exporter.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from routecollector.planner.planner import PlannedRoute


@dataclass(slots=True, frozen=True)
class BirdExportResult:
    """Result of BIRD configuration generation."""

    path: Path
    changed: bool
    route_count: int


class BirdExporter:
    """Export planned routes to a BIRD static protocol configuration."""

    def __init__(self, output_file: Path) -> None:
        self._output_file = output_file

    def export(self, routes: list[PlannedRoute]) -> BirdExportResult:
        """Generate BIRD configuration if its content has changed."""

        content = self.render(routes)
        previous_content = self._read_existing_content()

        if previous_content == content:
            return BirdExportResult(
                path=self._output_file,
                changed=False,
                route_count=len(routes),
            )

        self._write_atomic(content)

        return BirdExportResult(
            path=self._output_file,
            changed=True,
            route_count=len(routes),
        )

    @staticmethod
    def render(routes: list[PlannedRoute]) -> str:
        """Render planned routes as BIRD configuration text."""

        ipv4_routes = sorted(
            (route for route in routes if route.family == 4),
            key=lambda route: route.prefix,
        )
        ipv6_routes = sorted(
            (route for route in routes if route.family == 6),
            key=lambda route: route.prefix,
        )

        lines = [
            "# Autogenerated by RouteCollector",
            "# Do not edit manually",
            "",
            "protocol static routecollector_static {",
            "    ipv4;",
            "",
        ]

        for route in ipv4_routes:
            lines.append(
                f"    route {route.prefix} blackhole; "
                f"# confidence={route.confidence} "
                f"source_ips={route.source_ips}"
            )

        lines.extend(
            [
                "}",
                "",
                "protocol static routecollector_static6 {",
                "    ipv6;",
                "",
            ]
        )

        for route in ipv6_routes:
            lines.append(
                f"    route {route.prefix} blackhole; "
                f"# confidence={route.confidence} "
                f"source_ips={route.source_ips}"
            )

        lines.extend(["}", ""])

        return "\n".join(lines)

    def _read_existing_content(self) -> str | None:
        """Read an existing generated configuration."""

        if not self._output_file.exists():
            return None

        return self._output_file.read_text(encoding="utf-8")

    def _write_atomic(self, content: str) -> None:
        """Atomically replace generated configuration."""

        self._output_file.parent.mkdir(parents=True, exist_ok=True)

        temporary_file = self._output_file.with_suffix(
            self._output_file.suffix + ".tmp"
        )
        temporary_file.write_text(content, encoding="utf-8")
        temporary_file.replace(self._output_file)
