"""
BIRD configuration exporter.
"""

from __future__ import annotations

from pathlib import Path

from routecollector.planner.planner import PlannedRoute


class BirdExporter:
    """Export planned routes to BIRD static protocol config."""

    def __init__(self, output_file: Path) -> None:
        self._output_file = output_file

    def export(self, routes: list[PlannedRoute]) -> Path:
        """Export routes to BIRD config file."""

        self._output_file.parent.mkdir(parents=True, exist_ok=True)

        lines = [
            "# Autogenerated by RouteCollector",
            "# Do not edit manually",
            "",
            "protocol static routecollector_static {",
            "    ipv4;",
            "",
        ]

        ipv4_routes = [route for route in routes if route.family == 4]
        ipv6_routes = [route for route in routes if route.family == 6]

        for route in ipv4_routes:
            lines.append(f"    route {route.prefix} blackhole;")

        lines.extend(
            [
                "}",
                "",
                "protocol static routecollector_static6 {",
                "    ipv6;",
                "",
            ]
        )

        for route in ipv6_routes:
            lines.append(f"    route {route.prefix} blackhole;")

        lines.append("}")
        lines.append("")

        content = "\n".join(lines)

        tmp_file = self._output_file.with_suffix(self._output_file.suffix + ".tmp")
        tmp_file.write_text(content, encoding="utf-8")
        tmp_file.replace(self._output_file)

        return self._output_file
